import Image from "next/image"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { formatDate } from "@/lib/utils"

// This would typically come from a CMS or database based on the slug
const article = {
  title: "The Future of Neural Interfaces",
  date: "2023-04-15",
  author: "Neo Cybernetic",
  category: "Technology",
  image: "/placeholder.svg?height=600&width=1200",
  content: `
    <p>Neural interfaces, also known as brain-computer interfaces (BCIs), have long been a staple of science fiction. From the neural links in William Gibson's "Neuromancer" to the mind-jacks of "The Matrix," the idea of directly connecting our brains to computers has captivated our imagination for decades.</p>
    
    <p>But what was once fiction is rapidly becoming reality. In recent years, we've seen remarkable advances in neural interface technology, with companies like Neuralink, CTRL-labs, and Kernel developing devices that can read and interpret brain activity with increasing accuracy.</p>
    
    <h2>The Current State of Neural Interfaces</h2>
    
    <p>Today's neural interfaces generally fall into two categories: invasive and non-invasive. Invasive interfaces, like those being developed by Neuralink, involve surgically implanting electrodes directly into the brain. These can provide highly precise readings but come with obvious medical risks.</p>
    
    <p>Non-invasive interfaces, on the other hand, use external sensors to detect brain activity through the skull. While safer, they currently offer lower resolution and accuracy compared to their invasive counterparts.</p>
    
    <p>Despite these limitations, both approaches have already enabled remarkable applications, from allowing paralyzed individuals to control robotic limbs to enabling "locked-in" patients to communicate.</p>
    
    <h2>The Next Decade: What to Expect</h2>
    
    <p>Over the next ten years, we can expect several major developments in neural interface technology:</p>
    
    <ol>
      <li><strong>Increased Resolution:</strong> Both invasive and non-invasive interfaces will become capable of reading and writing to smaller groups of neurons, enabling more precise control and feedback.</li>
      <li><strong>Miniaturization:</strong> Neural interface hardware will become smaller, less obtrusive, and potentially even invisible.</li>
      <li><strong>Wireless Capabilities:</strong> Future interfaces will likely be wireless, eliminating the need for physical connections to external devices.</li>
      <li><strong>AI Integration:</strong> Advanced AI algorithms will improve the interpretation of neural signals, making interfaces more intuitive and responsive.</li>
      <li><strong>Expanded Applications:</strong> Beyond medical uses, we'll see neural interfaces applied to gaming, productivity, communication, and more.</li>
    </ol>
    
    <h2>Implications for Human-Computer Interaction</h2>
    
    <p>The widespread adoption of neural interfaces could fundamentally transform how we interact with technology. Imagine being able to:</p>
    
    <ul>
      <li>Control your devices with thoughts alone, eliminating the need for physical input methods</li>
      <li>Experience virtual and augmented reality with perfect sensory fidelity</li>
      <li>Communicate with others through direct brain-to-brain links</li>
      <li>Access information instantly, without the need to look it up</li>
      <li>Enhance cognitive abilities through direct neural augmentation</li>
    </ul>
    
    <p>These capabilities would represent not just an evolution but a revolution in human-computer interaction, potentially changing our relationship with technology as profoundly as the smartphone or the internet.</p>
    
    <h2>Ethical Considerations</h2>
    
    <p>Of course, such powerful technology raises important ethical questions. Issues of privacy, security, identity, and autonomy will need to be carefully addressed as neural interfaces become more sophisticated and widespread.</p>
    
    <p>Who owns the data generated by your brain? How can we prevent unauthorized access to neural devices? Could neural interfaces be used to manipulate thoughts or behavior? These are just a few of the questions that society will need to grapple with.</p>
    
    <h2>Conclusion</h2>
    
    <p>The future of neural interfaces is both exciting and challenging. As this technology continues to advance, it promises to open up new possibilities for human capability and connection. But realizing its full potential will require not just technical innovation but also careful consideration of its broader implications.</p>
    
    <p>One thing is certain: the line between human and computer is becoming increasingly blurred, and the next decade will likely see that line fade further as neural interfaces become more sophisticated and widespread.</p>
  `,
}

export default function BlogPostPage({ params }: { params: { slug: string } }) {
  return (
    <div className="min-h-screen bg-white dark:bg-black text-gray-900 dark:text-white">
      {/* Light mode background */}
      <div className="fixed inset-0 z-0 dark:hidden">
        <div className="absolute inset-0 bg-gray-50"></div>
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(59,130,246,0.03),transparent_70%)]"></div>
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxkZWZzPjxwYXR0ZXJuIGlkPSJncmlkIiB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHBhdHRlcm5Vbml0cz0idXNlclNwYWNlT25Vc2UiPjxwYXRoIGQ9Ik0gNDAgMCBMIDAgMCAwIDQwIiBmaWxsPSJub25lIiBzdHJva2U9IiNmMWY1ZjkiIHN0cm9rZS13aWR0aD0iMC41Ii8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIiAvPjwvc3ZnPg==')] opacity-50"></div>
      </div>

      {/* Dark mode background */}
      <div className="fixed inset-0 z-0 hidden dark:block">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(4,92,180,0.15),transparent_70%)]"></div>
        <div className="absolute inset-0 bg-[linear-gradient(to_bottom,transparent,rgba(0,0,0,0.8)_70%)]"></div>
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxkZWZzPjxwYXR0ZXJuIGlkPSJncmlkIiB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHBhdHRlcm5Vbml0cz0idXNlclNwYWNlT25Vc2UiPjxwYXRoIGQ9Ik0gNDAgMCBMIDAgMCAwIDQwIiBmaWxsPSJub25lIiBzdHJva2U9IiMxNTMzNTciIHN0cm9rZS13aWR0aD0iMC41Ii8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIiAvPjwvc3ZnPg==')] opacity-20"></div>
      </div>

      <main className="relative z-10 py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            <Link
              href="/blog"
              className="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 mb-8"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Blog
            </Link>

            <article>
              <div className="mb-8">
                <div className="flex items-center gap-4 mb-4">
                  <span className="px-3 py-1 text-sm rounded-full bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-500/30 text-blue-700 dark:text-blue-400">
                    {article.category}
                  </span>
                  <span className="text-gray-500 dark:text-gray-400">{formatDate(article.date)}</span>
                </div>
                <h1 className="text-4xl md:text-5xl font-bold mb-6">{article.title}</h1>
                <div className="flex items-center">
                  <div className="w-10 h-10 rounded-full bg-linear-to-br from-blue-600 to-pink-500 mr-3"></div>
                  <span className="text-gray-600 dark:text-gray-300">By {article.author}</span>
                </div>
              </div>

              <div className="relative mb-12">
                <div className="absolute -inset-0.5 bg-linear-to-r from-blue-600 to-pink-600 rounded-lg blur-sm opacity-50"></div>
                <div className="relative rounded-lg overflow-hidden">
                  <Image
                    src={article.image || "/placeholder.svg"}
                    alt={article.title}
                    width={1200}
                    height={600}
                    className="w-full h-auto"
                  />
                </div>
              </div>

              <div
                className="prose prose-gray dark:prose-invert prose-blue max-w-none"
                dangerouslySetInnerHTML={{ __html: article.content }}
              />
            </article>

            <div className="mt-16 pt-8 border-t border-gray-200 dark:border-blue-900/40">
              <h3 className="text-2xl font-bold mb-6">Share this article</h3>
              <div className="flex gap-4">
                <button className="px-4 py-2 rounded-md bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-500/30 text-blue-700 dark:text-blue-400 hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-colors">
                  Twitter
                </button>
                <button className="px-4 py-2 rounded-md bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-500/30 text-blue-700 dark:text-blue-400 hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-colors">
                  LinkedIn
                </button>
                <button className="px-4 py-2 rounded-md bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-500/30 text-blue-700 dark:text-blue-400 hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-colors">
                  Facebook
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
